version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: eos-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LANG: C.UTF-8
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_eos:/var/lib/mysql

  redis:
    image: 'redis:6-alpine'
    container_name: eos-redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - .data/redis:/data

  api:
    image: proj-eos-api              
    container_name: proj-eos-api-app
    ports:
      - "8000:3002"  # Expose 3002 inside container on 8000 outside
    environment:
      - PORT=3002  
    env_file:
      - .env      
    depends_on:
      - mysql
      - redis
    restart: on-failure

volumes:
  db_eos: